### numpy scraps

In [2]:
import numpy as np

In [4]:
matrix = np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [7]:
matrix = np.arange(0,9).reshape(3,3)

In [8]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


## for blockworld

In [5]:
import numpy as np

# Create a 2D list of letters
letters_2d = [['a', 'b', 'c'], ['d', 'e', 'f']]

# Create a NumPy array from the 2D list
letters_2d_array = np.array(letters_2d)

print(letters_2d_array)

[['a' 'b' 'c']
 ['d' 'e' 'f']]


#### lets append onto this aray

In [14]:
letters_2d = [['a', 'b', 'c'], ['d', 'e', 'f']]

letters_2d.append(['v'])
print(letters_2d)
print(len(letters_2d))
print(len(letters_2d[1]))
print(letters_2d[0][2])

[['a', 'b', 'c'], ['d', 'e', 'f'], ['v']]
3
3
c


In [15]:
# quick check 

node1 = table_state=[[1, 2], [3, 4]]
node2 = table_state=[[3, 4], [1, 2]]

print(node1 == node2)

False


In [ ]:
# lets check the union of each sub list, so grab the first sublist, then check against each sublist in the second one. take the lowest value for each sublist loop. then do the same for the next sublist in the initial. 
# may need to exclude any with len(1) from this calculation

### ok lets declare all of the states from our network


In [17]:
initial = [["A", "B", "C"], ["D", "E"]]
goal = [["A", "C"], ["D", "E", "B"]]
state_1_1 = [["A", "B"], ["D", "E", "C"]]
state_1_2 = [["A", "B"], ["D", "E"], ["C"]]
state_2_1 = [["A"],["D","E","B"],["C"]]

state_test1 = [["D","E","B"],["C","A"]]
state_test2 = [["A","C"],["D","E","B"]]

#TODO: this is a problematic state, need to fix it
test_when_under = [["D","C"],["A","E","B"]]


In [22]:
def calculate_similarity(initial, goal):
    total_similarity = 0
    matched_elements = set()  # To track elements already matched

    # Loop through each sublist in the initial state
    for init_sublist in initial:
        init_set = set(init_sublist)
        max_similarity = 0
        
        # Compare the sublist to each sublist in the goal state
        for goal_sublist in goal:
            goal_set = set(goal_sublist)

            # Check how many elements are in the same position
            similarity = sum(1 for i, el in enumerate(init_sublist) 
                             if i < len(goal_sublist) and el == goal_sublist[i])
            
            # If the sublist in goal has just one element, don't penalize movement
            if len(goal_sublist) == 1 and list(goal_sublist)[0] in init_set:
                similarity = len(goal_sublist)  # No penalty for single-element sublists

            # Track the maximum similarity for the current sublist
            max_similarity = max(max_similarity, similarity)
        
        # Add the maximum similarity for this sublist to the total
        total_similarity += max_similarity
        matched_elements.update(init_set)

    return total_similarity


initial_similarity = calculate_similarity(initial, goal)
state_1_1_similarity = calculate_similarity(state_1_1, goal)
state_1_2_similarity = calculate_similarity(state_1_2, goal)


print("Similarity score for initial state:", initial_similarity)
print("Similarity score for state 1_1:", state_1_1_similarity)
print("Similarity score for state 1_2:", state_1_2_similarity)
print("Similarly score for state 2_1:", calculate_similarity(state_2_1, goal))
print("Similarly score for state test 1:", calculate_similarity(state_test1, goal))
print("Similarly score for state test 2:", calculate_similarity(state_test2, goal))
#TODO: this should be 0
print("Similarly score for state 2_1:", calculate_similarity(test_when_under, goal))


Similarity score for initial state: 3
Similarity score for state 1_1: 3
Similarity score for state 1_2: 3
Similarly score for state 2_1: 4
Similarly score for state test 1: 3
Similarly score for state test 2: 5
Similarly score for state 2_1: 3


In [23]:
def calculate_similarity(initial, goal):
    total_similarity = 0
    
    # Loop through each sublist in the initial state
    for init_sublist in initial:
        max_similarity = 0
        
        # Compare the sublist to each sublist in the goal state
        for goal_sublist in goal:
            similarity = 0
            
            # Compare elements in position until a mismatch is found
            for i, el in enumerate(init_sublist):
                if i >= len(goal_sublist) or el != goal_sublist[i]:
                    break  # Stop when we find the first mismatch
                similarity += 1  # Add to similarity for matching elements
        
            max_similarity = max_similarity if max_similarity > similarity else similarity
        
        # Add the maximum similarity for this sublist to the total
        total_similarity += max_similarity

    return total_similarity

print("Similarity score for initial state:", initial_similarity)
print("Similarity score for state 1_1:", state_1_1_similarity)
print("Similarity score for state 1_2:", state_1_2_similarity)
print("Similarly score for state 2_1:", calculate_similarity(state_2_1, goal))
print("Similarly score for state 2_1:", calculate_similarity(state_test1, goal))
print("Similarly score for state 2_1:", calculate_similarity(state_test2, goal))
#TODO: this should be 2
print("Similarly score for state 2_1:", calculate_similarity(test_when_under, goal))

Similarity score for initial state: 3
Similarity score for state 1_1: 3
Similarity score for state 1_2: 3
Similarly score for state 2_1: 4
Similarly score for state 2_1: 3
Similarly score for state 2_1: 5
Similarly score for state 2_1: 2


-----
#### ok, lets check the tree functions

In [35]:
for index, item in enumerate(goal):
    print(f"Index: {index}, Item: {item}")

print(sum(len(sublist) for sublist in goal))

print(goal)
print(goal[1][-1])

Index: 0, Item: ['A', 'C']
Index: 1, Item: ['D', 'E', 'B']
5
[['A', 'C'], ['D', 'E', 'B']]
B


#### bfs 

In [32]:
graph = {
  '5' : ['3','7'],
  '3' : ['2', '4'],
  '7' : ['8'],
  '2' : [],
  '4' : ['8'],
  '8' : []
}

visited = [] # List for visited nodes.
queue = []     #Initialize a queue

def bfs(visited, graph, node): #function for BFS
  visited.append(node)
  queue.append(node)

  while queue:          # Creating loop to visit each node
    m = queue.pop(0) 
    print (m, end = " ") 

    for neighbour in graph[m]:
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

# Driver Code
print("Following is the Breadth-First Search")
bfs(visited, graph, '5')    # function calling

Following is the Breadth-First Search
5 3 7 2 4 8 

--------------------------------------------------------------------------------------------





## Lets test opencv in this block

In [1]:
# https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html
import cv2 as cv

In [2]:
image = cv.imread("Scratches/images/danny.webp")
# cv.imshow("Display window",img)


In [4]:
if image is None:
    print("Error: Could not open or find the image.")
else:
    # Step 2: Display the image in a window
    cv.imshow('Image Window', image)

    # Step 3: Wait for a key event
    cv.waitKey(0)

    # Step 4: Close all OpenCV windows
    cv.destroyAllWindows()

### filters

In [20]:
image = cv.imread_color("Scratches/images/danny.webp")

AttributeError: module 'cv2' has no attribute 'imread_color'

## Here we are just going to have some scraps not related to numpy

In [10]:
action_case = {
    '1': 'a',
    '2': 'b',
    '3': 'c',
}

for action_index in action_case:
    action = action_case.get(print(action_case[action_index]))

a
b
c


In [31]:
parent_node = [['A'], ['D', 'E', 'B'], ['C']]
sub_node = [[], ['D', 'E', 'B'], ['C'], ['A']]
sorted_self = sorted([sorted(sublist) for sublist in parent_node])
sorted_other = sorted([sorted(sublist) for sublist in sub_node])
print(sorted_self == sorted_other)

False
